apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-kubectl
spec:
  resources:
    inputs:
    - name: workspace
      type: git
  params:
  - name: K8S_DIRECTORY_PATH
    description: Path to the directory for kubectl apply -f
  steps:
  - name: apply-config
    image: lachlanevenson/k8s-kubectl
    workingDir: /workspace/source
    command: ['kubectl']
    args:
    - apply
    - -f
    - $(inputs.params.K8S_DIRECTORY_PATH)
