apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: backend-sql
spec:
  params:
    - name: BUILDER_IMAGE
      description: The image on which builds will run
      default: backend-sql:latest
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: K8S_DIRECTORY_PATH
      description: Path to the directory for kubectl apply -f
      default: ./config
  resources:
    - name: workspace
      type: git
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      resources:
        inputs:
          - name: workspace
            resource: workspace
    - name: deploy
      runAfter: [build-and-push]
      taskRef:
        name: deploy-kubectl
      resources:
        inputs:
          - name: workspace
            resource: workspace
      params:
        - name: K8S_DIRECTORY_PATH
          value: $(params.K8S_DIRECTORY_PATH)
