apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-sql
spec:
  template:
    metadata:
      name: backend-sql-v2
    spec:
      containers:
        - name: apiserver
          image: jensdriller/backend-sql:latest
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "arm64"
